### ISSUE TITLE
Installation Windows 10

### ISSUE THREAD

**Issue by shakasom** [darribas/contextily#102]
I have got this error while installing:

```
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Shakur\AppData\Local\Temp\pip-install-swfgy9pe\rasterio\
```
I am using Windows 10. Anaconda Environment.

**Comment by jorisvandenbossche** [comment]
@shakasom that error comes from install rasterio, which needs GDAL and a C compiler installed if you want to install it with pip from source on Windows. 

But since you are using Anaconda, you can install pre-built packages with conda: eg `conda install rasterio`.

Contextily itself is also available on the conda-forge channel, so you can install this with conda as `conda install contextily --channel conda-forge`

**Comment by shakasom** [comment]
I have already Rasterio installed in my Anaconda environment. Tried reinstalling Rasterio and then Contextily but that did not work either. I used the conda installation and it is working now.
