### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by stevencollinscn** [darribas/contextily#47]
I wasn't able to install the package and the following error rasied. 

![image](https://user-images.githubusercontent.com/33796896/50533639-e9609200-0afb-11e9-8d90-95172548511c.png)

**Comment by jorisvandenbossche** [comment]
@stevencollinscn it is the installation of rasterio that fails. As the error message above says: "Building on Windows requires extra options ... Provide a path to gdal-config using a GDAL_CONFIG environment variable .."  
See also https://rasterio.readthedocs.io/en/latest/installation.html

But, since you are using Anaconda, I would recommend to use `

**Comment by jorisvandenbossche** [comment]
But, since you are using Anaconda, I would recommend to use `conda` instead of `pip` to install it: `conda install contextily`

**Comment by stevencollinscn** [comment]
@jorisvandenbossche I actually tried `conda install` but it would throw me a `PackagesNotFoundError`

**Comment by darribas** [comment]
Closing as it seems resolved. Thanks @jorisvandenbossche!
