### ISSUE TITLE
PySAL dependency?

### ISSUE THREAD

**Issue by sjsrey** [darribas/contextily#6]
First cell of [contextily_guide.ipynb](https://github.com/darribas/contextily/blob/master/contextily_guide.ipynb) requires pysal is installed. PySAL isn't listed in [requirements.txt](https://github.com/darribas/contextily/blob/master/requirements.txt)

Not sure if PySAL is an intended dependency?

**Comment by darribas** [comment]
Right, not completely intuitively, the guide uses more libraries than are strictly required to run `contextily`. This is because, by itself, `contextily` only fetches tiles, but I wanted to display how you can use those in combination with other libraries of the eco-system to, for example, overlay raster data on top of them.

To be clear: you don't **need** `PySAL` to run `contextily`, although I highly recommend to use both in conjuction ;-)

**Comment by sjsrey** [comment]
Good point. This could be closed then as it is not a bug😁
