### ISSUE TITLE
API: specify the basemap / tile source (online tile provider, local file)

### ISSUE THREAD

**Issue by jorisvandenbossche** [darribas/contextily#90]
https://github.com/darribas/contextily/pull/66 is adding new definitions of online providers (which information is encoded in a dictionary with a 'url' key and additional metadata, similar as what ipyleaflet is doing: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py)

That PR sparked some discussion about the API how to specify this basemap "source". See https://github.com/darribas/contextily/pull/66#issuecomment-517176827 and subsequent comments.

**Comment by jorisvandenbossche** [comment]
So trying to summarize the discussion in the other issue:

Current situation:

- Many functions (`add_basemap`, `bounds2img`,  `bounds2raster`, ..) have currently a `url` keyword:
  - For `bounds2img`/`bounds2raster`, this can only be a reference to an online provider (I think?), while for `add_basemap` this can also be a path to a local file.
  - With the new providers module, this "url" can now also be a dictionary with several keys (including an "url" key) in addition to a string (url to be formatted), so the keyword name "url" might not be perfect anymore. 
    It can be unintuitive that `url` can take a string or a dict that, among other things, has a `url` with a string.

So that gives some options / questions:

- Should local files have their own keyword (maybe `path`)?
- Should we use a new keyword for the provider dict (maybe `provider`)? And should this accept a plain url string, or should we keep those as separate keywords?
- Both online tiles _and_ local files can also be specified with a `provider` object, which is a `dict` that contains all the arguments needed. This would allow having a `url` or a `path` in the dict and using the `attribution`. Arguably, it'd be more useful for online providers but could serve a purpose for local files.

As I said in the other issue, *if* we go for multiple keywords, I would personally split on "functionality" (online tiles vs local file) and not on type (dict vs string).

**Comment by jorisvandenbossche** [comment]
That gives some concrete options:

- Keep as is: `url` can take all of url string, provider dict or local file path string
- Split in `url` and `path`: `url` for online tiles as url string or provider dict and `path` as local file path string
- Split in `provider` and `path`: `provider` for online tiles as url string or provider dict and `path` as local file path string
- Split in `url`, `provider` and `path`: `url` still for string urls, `provider` for the full dict, and `path` as local file path string
- Keep a single keyword (variant of first option), but rename it to eg `source` (to not have the confusing "url" name for things that are not urls).
- ...

Other options? Preferences?

(note: I think any of the above can be done in a smooth way with providing deprecation warnings for the existing way where needed)

**Comment by darribas** [comment]
Thanks for the summary @jorisvandenbossche! My personal preference would be to keep `url` to maintain backward compatibility (I could be ammened to break that but, if we can avoid it, I think it's better), so you can pass a url string or a local path; and add a new argument called `provider` that is the dict structure we've been using.

My sense here is that the user would have two alternatives:

1. Fill in the details herself (pass a `url`, a `zoom`, etc.)
2. Go with what we provide and just pass a provider object

The user would then override anything from the provider explicitly by passing the provider object _and_ specific arguments (e.g. the zoom level).

This would only break the API in rc, so I'm better with that, and I think it's more encompassing. What do you think?

**Comment by jorisvandenbossche** [comment]
(added that to the options above)

> The user would then override anything from the provider explicitly by passing the provider object and specific arguments (e.g. the zoom level).

Note that the provider dict does not hold the zoom level (it only has information about a *maximum* zoom level, but this is not the same as the `zoom` specified for this specific plot). So this argument is currently only relevant for the `attribution` keyword I think.

> My personal preference would be to keep url to maintain backward compatibility (I could be ammened to break that but, if we can avoid it, I think it's better)

Just to be clear: I think all of the options can be done in a backwards compatible manner in the strict sense: it doesn't need to break users code directly. We can keep the existing `url` for a long time for back compat, at some point with a deprecation warning. 
Of course, not keeping the `url` long term indeed still means users will need to change their code at some point, so it's not backwards compatible in that sense that it needs some user action at some point in the future.

**Comment by jorisvandenbossche** [comment]
I don't have a strong opinion on what name to use (url, source, provider, ..) or whether to split off the local file into a `

**Comment by jorisvandenbossche** [comment]
I don't have a strong opinion on what name to use (url, source, provider, ..) or whether to split off the local file option into a separate `path` keyword. But splitting the web tiles into two keywords (depending on str vs dict) feels very strange to me. To repeat what I said in the other issue:

If we create new keywords, instead of splitting it based on the type like string (url) vs dict (provider), I would rather split it for functionality: online tile provider vs single local file. 
In the end, a single url string could be seen as "just" a short-hand for passing `{'url': url_string}` that can be easily supported, also in the new provider keyword. While the local file path is really different: it signifies a local file (not url of tile provider) and a single file (not a bunch of tiles).

So in your hypothetical "what the ideal API would be if we didn't have the legacy we have?", I would personally not add 2 different keywords to specify the web tile provider. Because in the end, whether the user is passing a single url string, or the more information complete dict that includes this url, in both cases the user is trying to specify the source from which to download the web tiles (and also in a very similar way: by providing a url string (whether directly or in a dict) that has {x}{y}{z} to be formatted).

**Comment by darribas** [comment]
My sense is more that the provider object is an alternative that offers slightly different functionality in that it populates the url, provides info on zoom, helps manage login's, etc. while the url is a very simple method. I'd vote to keep both because if someone has a unique url that works in the standard XYZ way, they can pass it directly to `url` without creating dicts or anything, while for "official" sources, we can provide a provider object with all required info. One gives you a barebone access to basemaps, the other more of a "service" with everything that's required, is how I see it.

So, to me, the split is not really between dict/str but between degrees of "service" provided. But I might be too narrow focused and too set in the original way, so not really good to answer the question of how it'd be best done if we didn't have legacy. Maybe it's not so hard to do `provider={'url': http...}`?

**Comment by jorisvandenbossche** [comment]
> I'd vote to keep both because if someone has a unique url that works in the standard XYZ way, they can pass it directly to url without creating dicts or anything,

To be clear, I never proposed to no longer allow people to pass a simple url string with {x}{y}{z}. I only tried to argue that for me it seems strange to introduce two separate keywords to either provide the url string or to provide the url dict. As in the end, both do exactly the same, and the simple url string is just a short-hand (that we keep supporting) for {"url": "url_string"}. So therefore, I would keep the simple url string / provider dict in a single keyword.

---

Personally, I would go for one of those options:

- Just keep all in a single keyword (like we have now `url`), but maybe rename to `source` to make the keyword less confusing (but keep `url` as alias of it for backwards compatibility)
- Have one keyword for online tile providers and one keyword for local file paths (pointing to a single image), eg `source` and `path`. 

---

If we don't have a clear preference / agreement, I would propose to go with my first bullet point just above: just keep a single keyword, which is basically as it is now on master (but only use `source` as name and keep `url` as alias). This seems the most conservative / in line with what we already have, and isn't much work to do. 

If that has a go (or one of the other options), I can do a PR next week, and we can release one of the coming weeks :-)

**Comment by jorisvandenbossche** [comment]
cc @ljwolf

**Comment by darribas** [comment]
Thank you very much @jorisvandenbossche for laying out the options and your patience with the back and forth. I've re-read the thread and had a second reflection on all this. I think I'm much closer to your views than when I wrote it in november.

The more I think about it, the simpler it seems to have a new `source` attribute to which you can pass anything suggesting a source of basemaps and it "just works", almost magically. From the user's perspective, it now seems pretty straightforward. I agree also on keeping the `url` argument so we don't break backwards compatibility (maybe we can add a deprecation warning before routing the objects to `source` and get rid of it eventually). While we're at it, we could also throw a deprecation warning on the [`tile_providers`](https://github.com/darribas/contextily/blob/master/contextily/tile_providers.py) module as it currently stands because it's superseded by the new `providers` architecture.

Thinking about this, it would also work seamlessly if we eventually add support for local versions of XYZ tiles (#117), we'd just need to check whether the local path is a raster or a folder structure.

So, I'm +1 on your first bullet. To see if we're on the same page, is this what's left to do?

- [ ] Add a `source` argument that can take either a `providers`-like dict, or a XYZ-type of url, or a path to a local raster.
- [ ] Alias the behaviour of `source` on `url` and include a deprecation warning for the argument.
- [ ] Add a deprecation warning to the current `tile_providers` module as it's a simple list of XYZ url's and it's superseded by the new providers API.

That'd be my bare minimum for 1.0, no? :-)

**Comment by ljwolf** [comment]
That looks reasonable to me!

**Comment by ljwolf** [comment]
I should also say, I'm happy that we're keeping a single argument for source that takes a dict or a string. I think that's the better, more flexible solution (over adding new singly-typed keyword arguments) until python gets fully in board with multiple dispatch :smile:
